### ISSUE TITLE
Parsing json

### ISSUE THREAD

**Issue by Isaac-Leonard** [alshdavid/TypeScriptBC#35]
JSON is pretty much key to javascript and typescript and without proper handling of it BorrowScript would be rather limited.
Parsing json in a type safe way in a statically compiled language almost seems impossible to me without a lot of boilerplate code.
Would it be possible to include something like Zod in the STL to allow for type safe parsing of external JSON while keeping type safety?
https://github.com/colinhacks/zod

**Comment by alshdavid** [comment]
This would be a standard library feature. We may not have structural types so explicit typing and casting will be required.

```typescript
import json from '@std/json'

type TargetJson = {
  hello: string
}

function main() {
  const target = '{ "hello": "world" }'
  const parsed = json.fromString<TargetJson>(target)
}

```
